# Generated by Django 3.2.19 on 2023-05-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_on']},
        ),
    ]
