# Generated by Django 3.2.19 on 2023-05-16 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsapp', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default=uuid.UUID('22ed8c9a-434c-4d81-b704-516ab8869ab6'), editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
